using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading;

namespace TeleprompterApp;

/// <summary>
/// Localization service. Supports Italian (it) and English (en).
/// Language is set from UserPreferences; user can switch via toolbar selector.
/// </summary>
internal static class Localization
{
    private const string DefaultCulture = "en";
    private static string _currentCulture = DefaultCulture;

    private static readonly Dictionary<string, string> It = new(StringComparer.OrdinalIgnoreCase)
    {
        // Status
        ["Status_Ready"] = "Pronto",
        ["Status_LoadFile"] = "Carica un file di testo o inizia a scrivere...",
        ["Status_ReadyLoadFile"] = "Pronto: carica un file o scrivi il tuo copione.",
        ["Status_Restored"] = "Ripristinato: {0}",
        ["Status_Loaded"] = "Caricato: {0}",
        ["Status_Imported"] = "Importato: {0}",
        ["Status_Saved"] = "Salvato: {0}",
        ["Status_SavedPlain"] = "Salvato (solo testo): {0}",
        ["Status_SavedFull"] = "Salvato come documento completo: {0}",
        ["Status_SaveCancelled"] = "Salvataggio annullato.",
        ["Status_NewReady"] = "Nuovo copione pronto.",
        ["Status_ImportingWord"] = "Importazione Word in corso...",
        ["Status_ScreensDetected"] = "Schermi rilevati: {0}",
        ["Status_ScreenActive"] = "Schermo attivo: {0}",
        ["Status_NoMonitor"] = "Nessun monitor rilevato",
        ["Status_PresenterOn"] = "Presenter su {0}",
        ["Status_PresenterHidden"] = "Presenter nascosto: usa un display esterno per attivarlo.",
        ["Status_Scrolling"] = "Scorrimento attivo",
        ["Status_Paused"] = "In pausa",
        ["Status_EndOfText"] = "Fine del testo",
        ["Status_StartOfText"] = "Inizio del testo",
        ["Status_AtStart"] = "Inizio testo",
        ["Status_AtEnd"] = "Fine testo",
        ["Status_SpeedZero"] = "Velocità azzerata",
        ["Status_SpeedPause"] = "Velocità 0: pausa",
        ["Status_ScrollReverse"] = "Scorrimento inverso",
        ["Status_ArrowUpdated"] = "Freccia aggiornata",
        ["Status_PresetSaved"] = "Preset {0} salvato",
        ["Status_PresetEmpty"] = "Preset {0} vuoto",
        ["Status_PresetLoaded"] = "Preset {0} caricato",
        ["Status_MarginsLinked"] = "Margini collegati: modifica uno = modifica tutti",
        ["Status_MarginsIndividual"] = "Margini individuali",
        ["Status_MarginsSet"] = "Margini L=D impostati a {0}",
        ["Status_ArrowColorUpdated"] = "Colore freccia aggiornato",
        ["Status_AtStartShort"] = "Testo riportato all'inizio",
        ["Status_TimerReset"] = "Timer azzerato",
        ["Status_GoToEnd"] = "Vai alla fine del testo",
        ["Status_OnAirOn"] = "On-Air attivo: testo bloccato, schermo esterno = preview",
        ["Status_OnAirOff"] = "On-Air spento: modifica script, relatore vede in diretta",
        ["Status_DragLoaded"] = "Caricato da drag & drop: {0}",
        ["Status_DragText"] = "Testo applicato dal trascinamento.",
        ["Status_NDIActive"] = "Trasmissione NDI attiva.",
        ["Status_NDIInactive"] = "Trasmissione NDI disattivata.",
        ["Status_NDIUnavailable"] = "NDI non disponibile: contenuto non pronto.",
        ["Status_NDIStartFailed"] = "Impossibile avviare NDI: installa il runtime NewTek.",
        ["Status_NDIRestartFailed"] = "Impossibile riavviare NDI con le impostazioni correnti.",
        ["Status_OSCUnavailable"] = "OSC non disponibile (porta {0}).",
        ["Status_CompanionUnavailable"] = "Companion non disponibile (porta {0}).",
        ["Status_OSCReset"] = "OSC: riposizionamento all'inizio",
        ["Status_CompanionPlay"] = "Companion: play",
        ["Status_CompanionPause"] = "Companion: pausa",
        ["Status_CompanionSpeedUp"] = "Companion: velocità +",
        ["Status_CompanionSpeedDown"] = "Companion: velocità -",
        ["Status_CompanionSpeedZero"] = "Companion: velocità 0",
        ["Status_CompanionSpeed"] = "Companion: velocità {0}",
        ["Status_EditorNotReady"] = "Impossibile salvare: editor non pronto.",
        ["Status_SyncPresenter"] = "Sync presenter: {0}",
        ["Status_ErrorScreen"] = "Errore display esterno: {0}",
        ["Error_OpenFile"] = "Impossibile aprire il file.\n{0}",
        ["Error_SaveFile"] = "Impossibile salvare il file.\n{0}",
        ["Error_DragFile"] = "Impossibile aprire il file trascinato.\n{0}",
        ["Error_Companion"] = "Companion errore: {0}",
        ["Error_Unhandled"] = "Si è verificato un errore imprevisto: {0}\nI dettagli sono stati salvati nei file di log.",
        ["Error_Title"] = "Errore",
        ["Question_LimitedFormat"] = "Il formato scelto non conserva la formattazione. Vuoi salvarlo come Documento Teleprompter (.rstp) per mantenere colori, font e stile?",
        ["Title_LimitedFormat"] = "Formato limitato",
        // UI - Toolbar
        ["Tooltip_Open"] = "Apri (Ctrl+O)",
        ["Tooltip_New"] = "Nuovo (Ctrl+N)",
        ["Tooltip_Save"] = "Salva (Ctrl+S)",
        ["Tooltip_FontSize"] = "Dimensione font",
        ["Tooltip_Font"] = "Font",
        ["Tooltip_Background"] = "Sfondo",
        ["Tooltip_TextColor"] = "Colore testo",
        ["Tooltip_Start"] = "Inizio (Home)",
        ["Tooltip_PlayPause"] = "Avvia / Pausa (Spazio in modalità non-modifica)",
        ["Tooltip_End"] = "Fine (End)",
        ["Tooltip_OnAir"] = "On-Air ON: testo bloccato, schermo esterno=preview. Off: modifica script, relatore vede modifiche in diretta",
        ["Tooltip_Mirror"] = "Specchio",
        ["Tooltip_TopMost"] = "Sempre in primo piano",
        ["Tooltip_Language"] = "Lingua / Language",
        ["Tooltip_LeftMargin"] = "Margine sinistro (testo dopo freccia)",
        ["Tooltip_LeftShort"] = "Sinistra (dopo freccia)",
        ["Tooltip_RightMargin"] = "Destro",
        ["Tooltip_RightShort"] = "Destro",
        ["Tooltip_LinkMargins"] = "Imposta L=D (margini sinistro e destro uguali)",
        ["Tooltip_MarginsLinked"] = "Margini insieme (attivo) / individuali: modifica un margine = modifica tutti quando attivo",
        ["Tooltip_TopMargin"] = "Alto",
        ["Tooltip_TopShort"] = "Alto",
        ["Tooltip_BottomMargin"] = "Basso",
        ["Tooltip_BottomShort"] = "Basso",
        ["Tooltip_ArrowSize"] = "Dimensione freccia",
        ["Tooltip_Arrow"] = "Freccia: colore e opzioni (trascina per posizione)",
        ["Tooltip_PresetSave"] = "Salva preset {0}",
        ["Tooltip_PresetLoad"] = "Carica preset {0}",
        ["Tooltip_TimerReset"] = "Azzera timer (anche con Home/Inizio)",
        ["Tooltip_MarginLeftThumb"] = "Trascina per margine sinistro",
        ["Tooltip_MarginRightThumb"] = "Trascina per margine destro",
        ["Tooltip_MarginTopThumb"] = "Trascina per margine alto",
        ["Tooltip_MarginBottomThumb"] = "Trascina per margine basso",
        ["Btn_Play"] = "Avvia",
        ["Btn_Pause"] = "Pausa",
        ["Btn_OnAir"] = "ON AIR",
        ["Btn_Off"] = "OFF",
        ["Btn_Reset"] = "Reset",
        ["Btn_Arrow"] = "Freccia",
        ["Btn_ArrowColor"] = "Colore freccia",
        ["Popup_ArrowTitle"] = "Freccia guida",
        ["Label_Margins"] = "Margini:",
        ["Label_Left"] = "L",
        ["Label_Right"] = "D",
        ["Label_Top"] = "A",
        ["Label_Bottom"] = "B",
        ["Label_Arrow"] = "Freccia:",
        ["Label_Preset"] = "Preset:",
        ["Display_Primary"] = " • Principale",
        ["Display_Number"] = "Schermo {0}",
        ["Display_Screen"] = "Schermo {0}x{1}",
        ["Title_Presenter"] = "Presenter",
        ["Title_OpenDialog"] = "Apri copione",
        ["Title_SaveDialog"] = "Salva copione",
        ["Filter_Open"] = "Documento Teleprompter (*.rstp)|*.rstp|Microsoft Word (*.docx;*.doc)|*.docx;*.doc|Formati ricchi (*.rtf;*.xaml;*.xamlpackage)|*.rtf;*.xaml;*.xamlpackage|Testo e sottotitoli|*.txt;*.md;*.srt;*.vtt;*.log;*.csv;*.json;*.xml;*.html;*.htm;*.yaml;*.yml;*.ini;*.cfg;*.bat;*.ps1|Tutti i file|*.*",
        ["Filter_Save"] = "Documento Teleprompter (*.rstp)|*.rstp|Rich Text Format (*.rtf)|*.rtf|FlowDocument XAML (*.xaml)|*.xaml|Testo semplice (*.txt)|*.txt|Tutti i file|*.*",
        ["DefaultScriptName"] = "Copione.rstp",
        ["Error_ReadFile"] = "Impossibile leggere il file: {0}",
        ["Label_SaveShortcut"] = "Ctrl+S",
    };

    private static readonly Dictionary<string, string> En = new(StringComparer.OrdinalIgnoreCase)
    {
        // Status
        ["Status_Ready"] = "Ready",
        ["Status_LoadFile"] = "Load a text file or start typing...",
        ["Status_ReadyLoadFile"] = "Ready: load a file or start typing your script.",
        ["Status_Restored"] = "Restored: {0}",
        ["Status_Loaded"] = "Loaded: {0}",
        ["Status_Imported"] = "Imported: {0}",
        ["Status_Saved"] = "Saved: {0}",
        ["Status_SavedPlain"] = "Saved (text only): {0}",
        ["Status_SavedFull"] = "Saved as full document: {0}",
        ["Status_SaveCancelled"] = "Save cancelled.",
        ["Status_NewReady"] = "New script ready.",
        ["Status_ImportingWord"] = "Importing Word...",
        ["Status_ScreensDetected"] = "Screens detected: {0}",
        ["Status_ScreenActive"] = "Active screen: {0}",
        ["Status_NoMonitor"] = "No monitor detected",
        ["Status_PresenterOn"] = "Presenter on {0}",
        ["Status_PresenterHidden"] = "Presenter hidden: use an external display to activate.",
        ["Status_Scrolling"] = "Scrolling",
        ["Status_Paused"] = "Paused",
        ["Status_EndOfText"] = "End of text",
        ["Status_StartOfText"] = "Start of text",
        ["Status_AtStart"] = "Start of text",
        ["Status_AtEnd"] = "End of text",
        ["Status_SpeedZero"] = "Speed set to zero",
        ["Status_SpeedPause"] = "Speed 0: paused",
        ["Status_ScrollReverse"] = "Reverse scrolling",
        ["Status_ArrowUpdated"] = "Arrow updated",
        ["Status_PresetSaved"] = "Preset {0} saved",
        ["Status_PresetEmpty"] = "Preset {0} empty",
        ["Status_PresetLoaded"] = "Preset {0} loaded",
        ["Status_MarginsLinked"] = "Margins linked: edit one = edit all",
        ["Status_MarginsIndividual"] = "Individual margins",
        ["Status_MarginsSet"] = "Margins L=R set to {0}",
        ["Status_ArrowColorUpdated"] = "Arrow color updated",
        ["Status_AtStartShort"] = "Text repositioned to start",
        ["Status_TimerReset"] = "Timer reset",
        ["Status_GoToEnd"] = "Go to end of text",
        ["Status_OnAirOn"] = "On-Air active: text locked, external screen = preview",
        ["Status_OnAirOff"] = "On-Air off: edit script, presenter sees changes live",
        ["Status_DragLoaded"] = "Loaded from drag & drop: {0}",
        ["Status_DragText"] = "Text applied from drag.",
        ["Status_NDIActive"] = "NDI transmission active.",
        ["Status_NDIInactive"] = "NDI transmission disabled.",
        ["Status_NDIUnavailable"] = "NDI unavailable: content not ready.",
        ["Status_NDIStartFailed"] = "Cannot start NDI: install NewTek runtime.",
        ["Status_NDIRestartFailed"] = "Cannot restart NDI with current settings.",
        ["Status_OSCUnavailable"] = "OSC unavailable (port {0}).",
        ["Status_CompanionUnavailable"] = "Companion unavailable (port {0}).",
        ["Status_OSCReset"] = "OSC: repositioned to start",
        ["Status_CompanionPlay"] = "Companion: play",
        ["Status_CompanionPause"] = "Companion: pause",
        ["Status_CompanionSpeedUp"] = "Companion: speed +",
        ["Status_CompanionSpeedDown"] = "Companion: speed -",
        ["Status_CompanionSpeedZero"] = "Companion: speed 0",
        ["Status_CompanionSpeed"] = "Companion: speed {0}",
        ["Status_EditorNotReady"] = "Cannot save: editor not ready.",
        ["Status_SyncPresenter"] = "Sync presenter: {0}",
        ["Status_ErrorScreen"] = "External screen error: {0}",
        ["Error_OpenFile"] = "Cannot open file.\n{0}",
        ["Error_SaveFile"] = "Cannot save file.\n{0}",
        ["Error_DragFile"] = "Cannot open dropped file.\n{0}",
        ["Error_Companion"] = "Companion error: {0}",
        ["Error_Unhandled"] = "An unexpected error occurred: {0}\nDetails have been saved to the log files.",
        ["Error_Title"] = "Error",
        ["Question_LimitedFormat"] = "The chosen format does not preserve formatting. Save as Teleprompter Document (.rstp) to keep colors, font and style?",
        ["Title_LimitedFormat"] = "Limited format",
        // UI - Toolbar
        ["Tooltip_Open"] = "Open (Ctrl+O)",
        ["Tooltip_New"] = "New (Ctrl+N)",
        ["Tooltip_Save"] = "Save (Ctrl+S)",
        ["Tooltip_FontSize"] = "Font size",
        ["Tooltip_Font"] = "Font",
        ["Tooltip_Background"] = "Background",
        ["Tooltip_TextColor"] = "Text color",
        ["Tooltip_Start"] = "Start (Home)",
        ["Tooltip_PlayPause"] = "Play / Pause (Space in non-edit mode)",
        ["Tooltip_End"] = "End (End)",
        ["Tooltip_OnAir"] = "On-Air ON: text locked, external screen=preview. Off: edit script, presenter sees changes live",
        ["Tooltip_Mirror"] = "Mirror",
        ["Tooltip_TopMost"] = "Always on top",
        ["Tooltip_Language"] = "Language / Lingua",
        ["Tooltip_LeftMargin"] = "Left margin (text after arrow)",
        ["Tooltip_LeftShort"] = "Left (after arrow)",
        ["Tooltip_RightMargin"] = "Right",
        ["Tooltip_RightShort"] = "Right",
        ["Tooltip_LinkMargins"] = "Set L=R (left and right margins equal)",
        ["Tooltip_MarginsLinked"] = "Margins linked (active) / individual: edit one = edit all when active",
        ["Tooltip_TopMargin"] = "Top",
        ["Tooltip_TopShort"] = "Top",
        ["Tooltip_BottomMargin"] = "Bottom",
        ["Tooltip_BottomShort"] = "Bottom",
        ["Tooltip_ArrowSize"] = "Arrow size",
        ["Tooltip_Arrow"] = "Arrow: color and options (drag to position)",
        ["Tooltip_PresetSave"] = "Save preset {0}",
        ["Tooltip_PresetLoad"] = "Load preset {0}",
        ["Tooltip_TimerReset"] = "Reset timer (also with Home/Start)",
        ["Tooltip_MarginLeftThumb"] = "Drag for left margin",
        ["Tooltip_MarginRightThumb"] = "Drag for right margin",
        ["Tooltip_MarginTopThumb"] = "Drag for top margin",
        ["Tooltip_MarginBottomThumb"] = "Drag for bottom margin",
        ["Btn_Play"] = "Play",
        ["Btn_Pause"] = "Pause",
        ["Btn_OnAir"] = "ON AIR",
        ["Btn_Off"] = "OFF",
        ["Btn_Reset"] = "Reset",
        ["Btn_Arrow"] = "Arrow",
        ["Btn_ArrowColor"] = "Arrow color",
        ["Popup_ArrowTitle"] = "Guide arrow",
        ["Label_Margins"] = "Margins:",
        ["Label_Left"] = "L",
        ["Label_Right"] = "R",
        ["Label_Top"] = "T",
        ["Label_Bottom"] = "B",
        ["Label_Arrow"] = "Arrow:",
        ["Label_Preset"] = "Preset:",
        ["Display_Primary"] = " • Primary",
        ["Display_Number"] = "Display {0}",
        ["Display_Screen"] = "Screen {0}x{1}",
        ["Title_Presenter"] = "Presenter",
        ["Title_OpenDialog"] = "Open script",
        ["Title_SaveDialog"] = "Save script",
        ["Filter_Open"] = "Teleprompter Document (*.rstp)|*.rstp|Microsoft Word (*.docx;*.doc)|*.docx;*.doc|Rich formats (*.rtf;*.xaml;*.xamlpackage)|*.rtf;*.xaml;*.xamlpackage|Text and subtitles|*.txt;*.md;*.srt;*.vtt;*.log;*.csv;*.json;*.xml;*.html;*.htm;*.yaml;*.yml;*.ini;*.cfg;*.bat;*.ps1|All files|*.*",
        ["Filter_Save"] = "Teleprompter Document (*.rstp)|*.rstp|Rich Text Format (*.rtf)|*.rtf|FlowDocument XAML (*.xaml)|*.xaml|Plain text (*.txt)|*.txt|All files|*.*",
        ["DefaultScriptName"] = "Script.rstp",
        ["Error_ReadFile"] = "Cannot read file: {0}",
        ["Label_SaveShortcut"] = "Ctrl+S",
    };

    public static string CurrentCulture => _currentCulture;

    public static void Initialize(string? cultureFromInstaller, string? cultureFromPreferences)
    {
        var culture = cultureFromInstaller ?? cultureFromPreferences ?? DefaultCulture;
        if (culture.Equals("en", StringComparison.OrdinalIgnoreCase))
            _currentCulture = "en";
        else
            _currentCulture = "it";

        Thread.CurrentThread.CurrentUICulture = new CultureInfo(_currentCulture);
    }

    /// <summary>Switch language at runtime (IT/EN). Call ApplyLocalization after.</summary>
    public static void SwitchLanguage(string culture)
    {
        _currentCulture = culture.Equals("en", StringComparison.OrdinalIgnoreCase) ? "en" : "it";
        Thread.CurrentThread.CurrentUICulture = new CultureInfo(_currentCulture);
    }

    public static string Get(string key)
    {
        var dict = _currentCulture == "en" ? En : It;
        return dict.TryGetValue(key, out var value) ? value : key;
    }

    public static string Get(string key, params object[] args)
    {
        var format = Get(key);
        return args.Length > 0 ? string.Format(format, args) : format;
    }
}
